# rule identifiers to exclude from running
disabled_rules:
  - type_body_length
  - function_body_length
  - file_length

# some rules are only opt-in
# Find all the available rules by running: swiftlint rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  # - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - static_over_final_class
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - explicit_self
  - unused_import

included:
  - Timer
  - TimerTests

excluded:
  - Timer/Keycodes.swift

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: 'xcode'
