language: objective-c
osx_image: xcode9.4
xcode_project: Timer.xcodeproj
xcode_scheme: Timer
xcode_destination: platform=macOS
script:
- xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
before_deploy:
- rm -rf "*.zip" || exit 0
- pushd "build/Release"
- zip -r "../../Timer.app.zip" "Timer.app/"
- popd
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aRVKjr56vhvz8BxEhCkhYTKhkr9hAadHwVFWxU6lCJ9+JXduR0lzd8lc7whoYXKtF2r3cz23ZkN+6qAB1kWUSykNhw0LqmMhO594z8VJuGQzj4Px+5pqp5N1pCDAa7Fi8xY+IgxwaU+0gOaRGz15yRNhpE1K0VDPwqxVlyJ9Y/wVAzgCae5uZKK6+Piq+zH7r4Ot99FZHcVeqhSZkcU7jIqNDhZaEA+7q7YceTHj2tNYRbB+hXDDLtm4CUsapkgHDDWp+NETQ+d47P5kPmlSga56+FamBAGeTAVwdu5CROCVYVUUPbQNFtx3FlAQXAhNzKsyVqnYoJbsso/B2DiubZDPr5SB3CLR+MJW/uq03+IN+MT3+GVFsYDFhYJRp3gfnEXD1HNY51gYmQ3hzgMVR8yiBxD0zweOPkALeei/n/Pt5j20f2o5EnxodPU/SBT+1jUNDdhx6Pboevo8gDVk2zxHHRWRQ5Okftfb5BZQwTH8Ix44q71RCb1tp7BLktnIG/FWGhFruuQN2JXVQHcGn81wIZ3qDQwDC4+EZdGdmKAkij/9NOZ5VKUSUDpLQ/S+/ngK/w/5gq45WQJwyu4CIg/4kECap6Ja3WloV/UXeyBddYnMBW4aDYmg5C6bDIRz0zFLhG2Z5hkvp3pCd5w8RMhO/fPxxCA7zLx0P9QC+10=
  file: Timer.app.zip
  on:
    repo: karbassi/timer-app
    branch: travis-setup
