#!/bin/sh
window=""
command=""

while [ $# -gt 0 ]; do
  case "$1" in
    -w|--window)
      window="$2"
      shift 2
      ;;
    *)
      command="$1"
      shift
      ;;
  esac
done

if [ -n "$window" ]; then
  open "timer://${command}?window=${window}"
else
  open "timer://${command}"
fi
